#!/data/data/com.termux/files/usr/bin/env bash

clear

Z="$(printf '\033[0m')"
R="$(printf '\033[1;31m')"
g="$(printf '\033[0;32m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

PORTRAIT=0
LANDSCAPE=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

# This script will configure a graphical user interface
# (xfce4) in ubuntu & ubuntu in termux.
# Creator : @ShivaShirsath

cd $HOME

dialog --colors --infobox "Installing Necessary Packages\n\nPlease wait…" 0 0
sleep 1

dialog --colors --infobox "Installing…\nxfce4 & basic apps" 0 0
sleep 1

echo ""

sudo apt install -y sudo wget apt-utils

sudo apt update -y
sudo apt upgrade -y

rm -rf /usr/local/bin/INSTALL
wget https://raw.githubusercontent.com/ShivaShirsath/Bash/main/INSTALL -O /usr/local/bin/INSTALL
chmod +x /usr/local/bin/*

sudo apt install -y git fish dialog xfce4 xfce4-goodies firefox fonts-indic fonts-emojione

sudo apt install -y git fish dialog xfce4 xfce4-goodies firefox fonts-indic fonts-emojione

sudo apt install -y git fish dialog xfce4 xfce4-goodies firefox fonts-indic fonts-emojione

dialog --colors --infobox "\Z1Removing…\nTheme & Icons.\Z0" 0 0
sleep 1

rm -rf /data/data/com.termux/files/usr/share/icons
rm -rf /data/data/com.termux/files/usr/share/themes
rm -rf /data/data/com.termux/files/usr/share/backgrounds
mkdir /data/data/com.termux/files/usr/share/backgrounds

rm -rf /usr/share/icons
rm -rf /usr/share/themes
rm -rf /usr/share/backgrounds

dialog --colors --infobox "Installing…\nTheme & Icons." 0 0
sleep 1

PWDx=$PWD
cd /data/data/com.termux/files/usr/share

rm -rf icons.tar.xz*
rm -rf themes.tar.xz*

wget https://github.com/ShivaShirsath/termux-desktop/raw/main/icons.tar.xz
wget https://github.com/ShivaShirsath/termux-desktop/raw/main/themes.tar.xz

tar -xvf icons.tar.xz
tar -xvf themes.tar.xz

rm -rf icons.tar.xz*
rm -rf themes.tar.xz*

cd backgrounds
wget https://raw.githubusercontent.com/ShivaShirsath/Ubuntu-On-Android/main/WhiteSur.svg

cd ../fonts
rm -rf CutiveMono.ttf
wget https://github.com/ShivaShirsath/Ubuntu-On-Android/raw/main/CutiveMono.ttf

cd $PWDx

PWDx=$PWD
cd /usr/share/

ln -s /data/data/com.termux/files/usr/share/themes themes
ln -s /data/data/com.termux/files/usr/share/icons icons
ln -s /data/data/com.termux/files/usr/share/backgrounds backgrounds

cd fonts
rm -rf CutiveMono.ttf
wget https://github.com/ShivaShirsath/Ubuntu-On-Android/raw/main/CutiveMono.ttf

cd $PWDx

dialog --colors --infobox "Setting… Config" 0 0

rm -rf $HOME/.backup
mkdir $HOME/.backup
mv $HOME/.config $HOME/.backup
mv $HOME/.vnc $HOME/.backup

cd $HOME

rm -rf .vnc.tar.gz
rm -rf .config.tar.gz

wget https://github.com/ShivaShirsath/Ubuntu-On-Android/raw/main/.vnc.tar.gz
wget https://github.com/ShivaShirsath/Ubuntu-On-Android/raw/main/.config.tar.gz

tar zxvf .vnc.tar.gz
tar zxvf .config.tar.gz

rm -rf .vnc.tar.gz
rm -rf .config.tar.gz

sudo apt update -y
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
sudo apt upgrade -y
sudo apt autoremove -y

dialog --colors --infobox "Installing…\nVisual Studio Code" 0 0
sleep 1

sudo apt install gnupg2 -y 
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt install apt-transport-https -y
sudo apt update -y
sudo apt install code -y
wget https://raw.githubusercontent.com/ShivaShirsath/Ubuntu-On-Android/main/code.desktop -O /usr/share/applications/code.desktop
chmod +x /usr/share/applications/*

#PWDx=$PWD
#cd $HOME
#rm -rf VNC
#git clone https://github.com/ShivaShirsath/VNC.git
#cd VNC
#chmod +x *
#bash install
#cd $PWDx

dialog --colors --infobox "Installing… Folders" 0 0
sleep 1

mkdir $HOME/Desktop
mkdir $HOME/Downloads
mkdir $HOME/Templates
mkdir $HOME/Public
mkdir $HOME/Documents
mkdir $HOME/Pictures
mkdir $HOME/Videos

wget https://raw.githubusercontent.com/ShivaShirsath/Ubuntu-On-Android/main/TermUX.desktop -O $HOME/Desktop/TermUX.desktop
chmod +x $HOME/Desktop/*

dialog --colors --title "👍" --ok-label "‎     Enjoy 🥳    " --msgbox "\nAll Done! \n\nUse \Z0\Zr‎ ubuntu ‎‎\ZR\Z0 cammand for login to CLI.\n\nUse \Z0\Zr‎ vnc ‎\ZR\Z0 cammand on CLI to start GUI.\n\n" 0 0
sleep 1

exit
